spring.application.name=socials
server.port=${SERVER_PORT:8081}

spring.liquibase.enabled=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/init.sql

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

socials.openapi.dev-url=http://localhost:8081
socials.openapi.prod-url=https://example.com
