CREATE TABLE users (
    id UUID PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL
);

CREATE TABLE posts (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users (id),
    title VARCHAR NOT NULL,
    text TEXT NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE images (
    id UUID PRIMARY KEY,
    post_id UUID NOT NULL REFERENCES posts (id),
    image_url TEXT NOT NULL
);

CREATE TABLE subscriptions (
    follower_id UUID NOT NULL REFERENCES users (id),
    followee_id UUID NOT NULL REFERENCES users (id),
    PRIMARY KEY (follower_id, followee_id)
);

CREATE TABLE friend_requests (
    id UUID PRIMARY KEY,
    sender_id UUID NOT NULL REFERENCES users (id),
    recipient_id UUID NOT NULL REFERENCES users (id),
    status VARCHAR NOT NULL
);

CREATE TABLE friendships (
    user_id UUID NOT NULL REFERENCES users (id),
    friend_id UUID NOT NULL REFERENCES users (id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE messages (
    id UUID PRIMARY KEY,
    sender_id UUID NOT NULL REFERENCES users (id),
    recipient_id UUID NOT NULL REFERENCES users (id),
    text TEXT NOT NULL
);

CREATE TABLE persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    username VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE persons_roles (
    role_id INT NOT NULL REFERENCES roles (id),
    person_id BIGINT NOT NULL REFERENCES persons (id),
    PRIMARY KEY (role_id, person_id)
);
